lr: 0.001
gamma: 0.99
tau: 0.005
batch_size: 100
step_per_collect: 2048
training_num_envs: 1
hidden_sizes: [64, 64]
learning_starts: 100
gradient_steps: 1
policy_noise: 0.2
update_actor_freq: 2
noise_clip: 0.5
exploration_sigma: 0.1
reward_normalization: false
estimation_step: 1
