policy: MlpPolicy
learning_rate: 3.0e-4
buffer_size: 1000000
learning_starts: 100
batch_size: 256
tau: 0.005
gamma: 0.99
train_freq: 1
gradient_steps: 1
ent_coef: auto
target_update_interval: 1
target_entropy: auto
use_sde: false
sde_sample_freq: -1
